name = "SphericalSpatialTrees"
uuid = "86b7679e-e8c0-4ea9-ad3d-baef5c69eb57"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
GeometryOps = "0.1.16"
LinearAlgebra = "1.11.0"
Rotations = "1.7.1"
StaticArrays = "1.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
